ASM/Controllers/DonhangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASM.Models;
using ASM.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ASM.Controllers
{
    public class DonhangController : BaseController
    {

        private IDonhangSvc _donhangSvc;

        public DonhangController(IDonhangSvc donhangSvc)
        {
            _donhangSvc = donhangSvc;
        }
        // GET: DonhangController
        public ActionResult Index()
        {
            return View(_donhangSvc.GetDonhangAll());
        }

        // GET: DonhangController/Details/5
        public ActionResult Details(int id)
        {
            return View(_donhangSvc.getDonhang(id));
        }

        // GET: DonhangController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DonhangController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DonhangController/Edit/5
        public ActionResult Edit(int id)
        {
            var donhang = _donhangSvc.getDonhang(id);
            return View(donhang);
        }

        // POST: DonhangController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection, Donhang donhang)
        {
            try
            {
                donhang.khachhang = null;
                _donhangSvc.EditDonhang(id, donhang);
                return RedirectToAction(nameof(Details), new { id = donhang.DonhangID});
            }
            catch
            {
                return View();
            }
        }

        // GET: DonhangController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DonhangController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ASM/Controllers/KhachhangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASM.Helpers;
using ASM.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ASM.Controllers
{
    public class KhachhangController : Controller
    {
        //private readonly IWebHostEnvironment _webHostEnvironment;
        private IKhachhangSvc _khachhangSvc;
        //private IUploadHelper _uploadHelper;
        public KhachhangController(IKhachhangSvc khachhangSvc)
        {
            //_webHostEnvironment = webHostEnvironment;
            _khachhangSvc = khachhangSvc;
            //_uploadHelper = uploadHelper;

        }
        // GET: KhachhangController
        public ActionResult Index()
        {
            return View(_khachhangSvc.GetKhachhangAll());
        }

        // GET: KhachhangController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: KhachhangController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KhachhangController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: KhachhangController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: KhachhangController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: KhachhangController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: KhachhangController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ASM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Trang chủ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_MenuPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ASM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ASM/Views/Shared/_MenuPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using ASM.Models
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Extensions
@using ASM.Constant

@{string userName = Context.Session.GetString(SessionKey.Nguoidung.UserName); }

@if (userName != null && userName != "")
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Nguoidung" asp-action="Index">Quản trị</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="MonAn" asp-action="Index">Món Ăn</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Donhang" asp-action="Index">Dơn hàng</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Khachhang" asp-action="Index">Khách hàng</a>
    </li>
}

ASM/Views/Shared/_WebLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        h1 {
            background-color: #17a2b8;
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-0 bg-warning text-dark font-weight-bold">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/login/logo-websitepng-9050.png" class="w-75" />
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trang Chủ</a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Thực Đơn</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_WebLoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_MenuPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ASM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ASM/Views/Shared/_WebLoginPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using ASM.Models
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Extensions
@using ASM.Constant

@{string emailAddress = Context.Session.GetString(SessionKey.Khachhang.KH_Email);}
@{string fullName = Context.Session.GetString(SessionKey.Khachhang.KH_FullName);}
@{string cart = Context.Session.GetString("cart");}

    <ul class="navbar-nav">
        <li class="nav-item">
            <a id="cart" class="nav-link text-dark" href="/Home/Cart">
                @if (cart != null && cart != "")
                {
                    <img id="imgCart" src="~/images/monan/cartA.png" style="width:30px" />
                }
                else
                {
                    <img id="imgCart" src="~/images/monan/cart.png" style="width:30px" />
                }
            </a>
        </li>
        @if (emailAddress != null && emailAddress != "")
        {
            <li class="nav-item">
                <a class="nav-link text-dark" id="information" href="/Home/Info">Xin Chào @fullName</a>
            </li>            
            <li class="nav-item">
                <a class="nav-link text-dark" id="history" href="/Home/History">Đơn hàng |</a>
            </li>
            <li class="nav-item">
                <form asp-area="" asp-controller="Home" asp-action="Logout" method="post" id="logoutForm">
                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                </form>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link text-dark" id="login" href="/Home/Login">Đăng nhập</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" id="register" href="/Home/Register">Đăng kí</a>
            </li>
        }
    </ul>